- name: qutebrowser - clone git repo
  git:
    repo: https://github.com/qutebrowser/qutebrowser.git
    dest: "{{ thirdparty }}/qutebrowser"
    force: yes

- name: qutebrowser - build
  command: tox -e mkvenv-pypi
  args:
    chdir: "{{ thirdparty }}/qutebrowser"

- name: qutebrowser - install /usr/bin/ script
  become: true
  template:
    src: qutebrowser.j2
    dest: "/usr/bin/qutebrowser"
    mode: 0755

- name: qutebrowser - unzip pdfjs
  unarchive:
    src: "{{ thirdparty }}/assets/pdfjs-2.1.266-dist.zip"
    dest: "{{ ansible_env.HOME }}/.local/share/qutebrowser/pdfjs"
