- name: dotfiles - clone repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    update: yes
  loop: "{{ dotfiles_repositories }}"

- name: dotfiles - create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ thirdparty }}"
    - "{{ ansible_env.HOME }}/.themes/"
    - "{{ ansible_env.HOME }}/.screenlayout/"

- name: dotfiles - untar theme
  unarchive:
    src: "{{ thirdparty }}/assets/oomox-nord.tar.gz"
    dest: "{{ ansible_env.HOME }}/.themes"

- name: dotfiles - copy passmenu
  copy:
    src: "{{ thirdparty }}/password-store/contrib/dmenu/passmenu"
    dest: "{{ ansible_env.HOME }}/.local/bin"
    mode: 0700

- name: dotfiles - copy notes
  copy:
    src: "{{ thirdparty }}/notes/notes"
    dest: "{{ ansible_env.HOME }}/.local/bin/notes"
    mode: 0700

- name: dotfiles - copy xkb_switch binary
  copy:
    src: "{{ xkb_switch_git_path }}/build/xkb-switch"
    dest: "{{ ansible_env.HOME }}/.local/bin"
    mode: 0700

- name: dotfiles - setup cronjob for repository syncing
  cron:
    name: "sync repo {{ item }}"
    special_time: hourly
    job: "{{ ansible_env.HOME }}/.dotfiles/bin/sync.sh {{ ansible_env.HOME }}/{{ item }}"
  loop:
    - Notes
    - .password-store

- name: dotfiles - copy syncthing service file
  copy:
    src: "{{ thirdparty }}/syncthing/etc/linux-systemd/user/syncthing.service"
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/syncthing.service"
    mode: 0700

- name: dotfiles - enable syncthing service
  systemd:
    name: syncthing
    enabled: yes
    masked: no
    scope: user
    state: started
