- name: Î™nstall all updates
  become: yes
  become_method: sudo
  apt:
    upgrade: dist
    update_cache: yes
    autoremove: yes
    autoclean: yes

- name: Install a list of packages
  become: yes
  become_method: sudo
  apt:
    name: "{{ item }}"
  with_items: "{{ ubuntu_packages }}"
