- name: Add apt keys
  when: ansible_distribution == 'Ubuntu'
  apt_key: 
    url: "{{ item }}"
    state: present
  with_items: "{{ ubuntu_apt_keys }}"

- name: Add apt repositories
  when: ansible_distribution == 'Ubuntu'
  apt_repository:
    repo: "{{ item }}"
  with_items: "{{ ubuntu_apt_repositories }}"

- name: Î™nstall all updates
  when: ansible_distribution == 'Ubuntu'
  apt:
    upgrade: full
    update_cache: yes
    autoremove: yes
    autoclean: yes

- name: Install a list of packages
  when: ansible_distribution == 'Ubuntu'
  apt:
    name: "{{ ubuntu_packages }}"
