---

i3lock_color_git_path: "{{ thirdparty }}/i3lock_color"

i3lock_color_gaps_dependencies:
  - libev-dev
  - libxcb-composite0
  - libxcb-composite0-dev
  - libxcb-xinerama0
  - libxcb-randr0
  - libxcb-xinerama0-dev
  - libxcb-xkb-dev
  - libxcb-image0-dev
  - libxcb-util-dev
  - libxkbcommon-x11-dev
  - libjpeg-turbo8-dev
  - libpam0g-dev
