- name: install i3-gaps
  pacman: name=i3-gaps
  become_user: root

- name: install gcc
  pacman: name=gcc
  become_user: root

- name: install xkb-switch
  aur: name=xkb-switch skip_installed=true

- name: fetch i3-utils
  git:
    repo: https://github.com/DictumMortuum/i3-utils.git
    dest: "{{ thirdparty }}/i3-utils"
    update: yes
  become_user: consul
  notify: make i3-utils

- name: fetch permutations
  git:
    repo: https://github.com/DictumMortuum/permutations.git
    dest: "{{ thirdparty }}/permutations"
    update: yes
  become_user: consul
  notify: make permutations
