- include: fonts.yml
- include: greenclip.yml
- include: i3.yml
- include: notable.yml
- include: qutebrowser.yml
- include: suckless.yml
- include: syncthing.yml
- include: theme.yml
- include: vscode.yml
