- block:
    - name: install go
      pacman: name=go
    - name: install fakeroot
      pacman: name=fakeroot
    - name: install binutils
      pacman: name=binutils
    - name: install awk
      pacman: name=awk
  become: yes
  become_user: root

- name: install fzf
  aur: name=fzf-git skip_installed=true
