- block:
    - name: install go
      pacman: name=go
    - name: install fakeroot
      pacman: name=fakeroot
  become: yes
  become_user: root

- name: install fzf
  aur: name=fzf-git skip_installed=true
