- block:
    - name: install go
      pacman: name=go
    - name: install fakeroot
      pacman: name=fakeroot
    - name: install binutils
      pacman: name=binutils
    - name: install awk
      pacman: name=awk
    - name: install file
      pacman: name=file
    - name: install patch
      pacman: name=patch
  become: yes
  become_user: root

- name: install fzf
  aur: name=fzf-git skip_installed=true
