- name: install zsh
  pacman: name=zsh state=present

- name: create "{{ zsh_cache }}"
  file: dest="{{ zsh_cache }}" state=directory

- name: create async.zsh link
  file:
    src: "{{ thirdparty }}/zsh-async/async.zsh"
    dest: "{{ zsh_cache }}/async"
    state: link

- name: create pure.zsh link
  file:
    src: "{{ thirdparty }}/pure/pure.zsh"
    dest: "{{ zsh_cache }}/prompt_pure_setup"
    state: link
