- apt:
    name:
      - libxkbfile-dev
      - cmake
  become: yes

- name: xkb_switch - clone repositories
  git:
    repo: git@github.com:ierton/xkb-switch.git
    dest: "{{ thirdparty }}/xkb_switch-git"
    update: yes
  notify:
    - delete xkb_switch build folder
    - create xkb_switch build folder
    - configure xkb_switch
    - compile xkb_switch
    - install xkb_switch
    - copy xkb_switch binary

- meta: flush_handlers
