- pacman:
    name: "{{ item }}"
  loop:
    - git
    - tcl
    - fakeroot
    - binutils
    - vim
    - awk
    - file
    - patch
    - go
    - pass
    - syncthing
    - jq
    - gcc
    - cronie

- name: install fzf
  aur: name=fzf-git skip_installed=true

- name: install xurls
  aur: name=xurls skip_installed=true

- cron:
    name: "sync repo {{ item }}"
    minute: "0,20,40"
    job: "{{ ansible_env.HOME }}/.local/bin/dotctl.sh sync-repo {{ ansible_env.HOME }}/{{ item }}"
  loop:
    - Notes
    - .password-store
