- name: create domus group
  group: name=domus gid=1992 state=present

- name: create arcanum group
  group: name=arcanum gid=16180 state=present

- name: create dimitris group
  group: name=dimitris gid=1986 state=present

- name: create petrina group
  group: name=petrina gid=1993 state=present

- name: create manolis group
  group: name=manolis gid=1956 state=present

- name: create fofi group
  group: name=fofi gid=1960 state=present

- name: create theoni group
  group: name=theoni gid=1989 state=present

- name: install sudo
  pacman: name=sudo state=present

- name: install vi
  pacman: name=vi state=present

- name: make dimitris a sudoer
  lineinfile:
    path: /etc/sudoers.d/dimitris
    state: present
    line: 'dimitris ALL=(ALL) NOPASSWD: ALL'
    create: True
    validate: /usr/sbin/visudo -cf %s

- user:
    name: dimitris
    group: dimitris
    groups: arcanum,domus
    append: yes
    uid: 1986
    create_home: True
    comment: "Dimitris Raviolos,,,"
    password: "{{ 'default' | password_hash('sha512') }}"
    update_password: on_create
  register: dimitris

- user:
    name: petrina
    group: petrina
    groups: domus
    append: yes
    uid: 1993
    create_home: True
    comment: "Petrina Raviolou,,,"
    password: "{{ 'default' | password_hash('sha512') }}"
    update_password: on_create
  register: petrina

- shell: chage -d 0 petrina
  when: petrina.changed

- user:
    name: manolis
    group: manolis
    groups: domus
    append: yes
    uid: 1956
    create_home: True
    comment: "Manolis Raviolos,,,"

- shell: passwd -d manolis

- user:
    name: fofi
    group: fofi
    groups: domus
    append: yes
    uid: 1960
    create_home: True
    comment: "Fofi Klironomou,,,"

- shell: passwd -d fofi

- user:
    name: theoni
    group: theoni
    groups: domus
    append: yes
    uid: 1989
    create_home: True
    comment: "Theoni Fytrou,,,"
    password: "{{ 'default' | password_hash('sha512') }}"
    update_password: on_create
  register: theoni

- shell: chage -d 0 theoni
  when: theoni.changed
