- name: vscode - add microsoft apt key
  apt_key: 
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: yes
  tags:
    - ubuntu

- name: vscode - add microsoft apt repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
  become: yes
  tags:
    - ubuntu

- name: vscode - install packages
  include_role:
    name: apt-install
  vars:
    apt_packages:
      - code
  tags:
    - ubuntu

- name: vscode - install extensions
  shell: code --install-extension "{{ item }}"
  loop:
    - arcticicestudio.nord-visual-studio-code
    - shaunlebron.vscode-parinfer
    - sleutho.tcl
  tags:
    - install
