- name: vscode - add microsoft apt key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: yes

- apt:
    name:
      - libx11-xcb1
      - libxcb1
      - libasound2
  become: yes

- name: vscode - add microsoft apt repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
  become: yes

- apt:
    name:
      - code
  become: yes

- name: vscode - install extensions
  shell: code --install-extension "{{ item }}"
  loop:
    - arcticicestudio.nord-visual-studio-code
    - shaunlebron.vscode-parinfer
    - sleutho.tcl
    - EditorConfig.EditorConfig
