---

- name: autoreconf i3-gaps
  command: autoreconf --force --install
  args:
    chdir: "{{ i3_gaps_git_path }}"

- name: delete i3-gaps build folder
  file:
    state: absent
    path: "{{ i3_gaps_git_path }}/build"

- name: create i3-gaps build folder
  file:
    state: directory
    path: "{{ i3_gaps_git_path }}/build"

- name: configure i3-gaps
  command: ../configure --prefix=/usr --disable-sanitizers
  args:
    chdir: "{{ i3_gaps_git_path }}/build"

- name: compile i3-gaps
  command: make
  args:
    chdir: "{{ i3_gaps_git_path }}/build"

- name: install i3-gaps
  command: make install
  args:
    chdir: "{{ i3_gaps_git_path }}/build"
  become: true
