- name: zsh - install packages
  include_role:
    name: apt-install
  vars:
    apt_packages: "{{ zsh_packages }}"

- name: zsh - create directories
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ zsh_directories }}"

- name: zsh - clone repositories
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    update: yes
  loop: "{{ zsh_repositories }}"

- name: zsh - symlink to fpath
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop: "{{ zsh_links }}"
