- name: Update packages
  hosts: all
  become: true
  tasks:
  - apt:
      upgrade: dist
      update_cache: yes
      autoremove: yes
      autoclean: yes
      cache_valid_time: 3600

  - apt:
      name: "{{ apt_packages }}"

  - apt_repository:
      repo: "{{ item }}"
    loop: "{{ apt_repositories }}"

  - apt:
      deb: "{{ item }}"
    loop: "{{ apt_debs }}"
    tags:
      - long
