---
- name: Playbook to manage dotfiles!
  hosts: localhost
  connection: local
  tasks:
    - name: Create folder
      file: path={{item}} state=directory
      with_items:
        - "~/.thirdparty/"
        - "~/.cache/ssh/"
        - "~/.cache/vim/"

#    - name: Install dotfiles
#      git: repo=git@github.com:DictumMortuum/dotfiles.git dest=~ separate_git_dir=~/.dotfiles.git

    - name: Install pure
      git: repo=git@github.com:sindresorhus/pure.git dest=~/.thirdparty/pure update=yes

    - name: Install zsh-async
      git: repo=git@github.com:mafredri/zsh-async.git dest=~/.thirdparty/zsh-async update=yes

    - name: Install vundle
      git: repo=git@github.com:VundleVim/Vundle.vim.git dest=~/.thirdparty/Vundle.vim update=yes

    - name: Install zsh-syntax-highlighting
      git: repo=git@github.com:zsh-users/zsh-syntax-highlighting.git dest=~/.thirdparty/zsh-syntax-highlighting update=yes

    - name: Install vundle plugins
      shell: vim -E -s -c "source ~/.vimrc" -c PluginInstall -c qa

    - name: Î™nstall all updates
      become: yes
      become_method: sudo
      apt:
        upgrade: dist
        update_cache: yes
        autoremove: yes
        autoclean: yes

    - name: Install a list of packages
      become: yes
      become_method: sudo
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - git
          - zsh
          - vim
          - unity-tweak-tool
          - gawk
          - tcl
