---
- name: Initialize user environment
  hosts: all
  tasks:
    - name: Create folder
      file: path={{item}} state=directory
      with_items:
        - ~/.thirdparty/
        - ~/.cache/ssh/
        - ~/.cache/vim/
        - ~/.cache/zsh/

- name: Provision ubuntu specific packages
  hosts: ubuntu
  roles:
    - ubuntu

- name: Provision packages from git repositories
  hosts: all
  roles:
    - git
