# https://color.firefox.com/?theme=XQAAAAIGAQAAAAAAAABBqYhm849SCia2CaaEGccwS-xNKlhV_t_v1qJFeSz0Bb1c1mzpnCmakaJhKqr6fIoyNBJJ-FEtzLP39_fcH6j5bjKsgxiCwJ7xWJXsBPAdf2RS8tq7QiV84xYWmk2z_FDrfacWeoZdb8cSZg978p0R7TilpkFqEAgjJALVLlhoFpMDyCCtvwsVYP19n6LtEhWKJMQ94yN6J8owC3DC5Hbg45__Ff-AAA

- import_playbook: apt.yml
- import_playbook: bootstrap.yml

- name: Install dotfiles
  hosts: all
  tasks:
  - name: copy files
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{ item.mode }}"
    loop: "{{ copy_files }}"

  - name: fetch files
    get_url:
      url: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{ item.mode }}"
    loop: "{{ fetch_files }}"

  - name: make install
    make:
      chdir: "{{ item }}"
      target: install
    loop: "{{ make_targets }}"

- name: Install applications
  hosts: all
  roles:
    - qutebrowser
    - dmenu
    - vscode
    - greenclip
    - i3-gaps
    - xkb-switch
    - notable
    - syncthing
