# https://color.firefox.com/?theme=XQAAAAIGAQAAAAAAAABBqYhm849SCia2CaaEGccwS-xNKlhV_t_v1qJFeSz0Bb1c1mzpnCmakaJhKqr6fIoyNBJJ-FEtzLP39_fcH6j5bjKsgxiCwJ7xWJXsBPAdf2RS8tq7QiV84xYWmk2z_FDrfacWeoZdb8cSZg978p0R7TilpkFqEAgjJALVLlhoFpMDyCCtvwsVYP19n6LtEhWKJMQ94yN6J8owC3DC5Hbg45__Ff-AAA

- name: Update packages
  hosts: all
  become: true
  tasks:
  - apt:
      upgrade: dist
      update_cache: yes
      autoremove: yes
      autoclean: yes
      cache_valid_time: 3600

  - apt:
      name: "{{ apt_packages }}"

  - apt_repository:
      repo: "{{ item }}"
    loop: "{{ apt_repositories }}"

  - apt:
      deb: "{{ item }}"
    loop: "{{ apt_debs }}"
    tags:
      - long

- name: Install dotfiles
  hosts: all
  tasks:
  - name: clone repositories
    git:
      repo: "{{ item.repo }}"
      dest: "{{ item.dest }}"
      update: yes
    loop: "{{ git_repositories }}"

  - name: create directories
    file:
      path: "{{ item }}"
      state: directory
    loop: "{{ directories }}"

  - name: symlink to zsh fpath
    file:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      state: link
    loop: "{{ zsh_links }}"

  - name: copy files
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      mode: "{{ item.mode }}"
    loop: "{{ copy_files }}"

  - name: untar theme
    unarchive:
      src: "{{ thirdparty }}/assets/oomox-nord.tar.gz"
      dest: "{{ ansible_env.HOME }}/.themes"

  - name: setup cronjob for repository syncing
    cron:
      name: "sync repo {{ item }}"
      special_time: hourly
      job: "{{ ansible_env.HOME }}/.dotfiles/bin/sync.sh {{ ansible_env.HOME }}/{{ item }}"
    loop:
      - Notes
      - .password-store

  - name: duplicates - make install
    make:
      chdir: "{{ thirdparty }}/duplicates"
      target: install

  - name: vim - install vundle plugins
    shell: vim -E -s -c "source {{ ansible_env.HOME }}/.vimrc" -c PluginInstall -c qa

- name: Install applications
  hosts: all
  roles:
    - vscode
    - greenclip
    - i3-gaps
    - xkb-switch
    - notable
    - boostnote
    - syncthing
