---
- name: Full desktop provision
  hosts: all
  roles:
    - apt-upgrade
    - dotfiles
    - zsh
    - vim
    - vscode
    - greenclip
    - i3
    - i3-gaps
    - xkb-switch
    - boostnote
    - gitkraken
    - syncthing
