- import_playbook: users.yml

- hosts: all
  tasks:
    - pacman:
        name: git

    - pacman:
        name: tcl

- hosts: all
  become: yes
  become_user: dimitris
  tasks:
    - pacman:
        name: git
        state: present

    - copy:
        src: "~/Sync/Secret/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.ssh/{{ item }}"
        mode: 0600
      with_items:
        - id_rsa.pub
        - id_rsa

    - git:
        repo: git@gitlab.com:DictumMortuum/notes.git
        dest: "{{ ansible_env.HOME }}/Notes"
        update: yes

    - git:
        repo: git@gitlab.com:DictumMortuum/pass.git
        dest: "{{ ansible_env.HOME }}/.password-store"
        update: yes

- hosts: all
  become: yes
  become_user: dimitris
  roles:
    - setup-dotfiles

- hosts: all
  become: yes
  become_user: fofi
  roles:
    - setup-dotfiles

- hosts: all
  become: yes
  become_user: manolis
  roles:
    - setup-dotfiles

- hosts: all
  become: yes
  become_user: theoni
  roles:
    - setup-dotfiles

- hosts: all
  become: yes
  become_user: petrina
  roles:
    - setup-dotfiles
