- hosts: all
  become: yes
  roles:
    - setup-users

- hosts: all
  tasks:
    - pacman:
        update_cache: yes

    - pacman:
        name: "{{ item }}"
      loop:
        - git
        - tcl
        - fakeroot
        - binutils
        - vim
        - awk
        - file
        - patch
        - go
        - pass
        - syncthing
        - jq
        - gcc
        - cronie

    - file:
        name: "{{ thirdparty }}"
        group: domus
        mode: '0775'
        state: directory

- hosts: all
  become: yes
  become_user: dimitris
  roles:
    - setup-base
    - setup-dotfiles
    - setup-zsh
    - setup-desktop

- hosts: all
  become: yes
  become_user: fofi
  roles:
    - setup-dotfiles
    - setup-zsh

- hosts: all
  become: yes
  become_user: manolis
  roles:
    - setup-dotfiles
    - setup-zsh

- hosts: all
  become: yes
  become_user: theoni
  roles:
    - setup-dotfiles
    - setup-zsh

- hosts: all
  become: yes
  become_user: petrina
  roles:
    - setup-dotfiles
    - setup-zsh
