- hosts: all
  become: yes
  tasks:
    - name: update pacman cache
      pacman: update_cache=yes
  roles:
    - setup-users

- hosts: all
  become: yes
  become_user: dimitris
  roles:
    - setup-thirdparty
    - setup-dotfiles
    - setup-zsh
    - setup-desktop

- hosts: all
  become: yes
  become_user: fofi
  roles:
    - setup-dotfiles
    - setup-zsh

- hosts: all
  become: yes
  become_user: manolis
  roles:
    - setup-dotfiles
    - setup-zsh

- hosts: all
  become: yes
  become_user: theoni
  roles:
    - setup-dotfiles
    - setup-zsh

- hosts: all
  become: yes
  become_user: petrina
  roles:
    - setup-dotfiles
    - setup-zsh
