- hosts: all
  become: yes
  roles:
    - setup-users

- hosts: all
  become: yes
  become_user: consul
  roles:
    - setup-thirdparty

- hosts: all
  become: yes
  become_user: dimitris
  roles:
    - setup-ssh
    - setup-dotfiles

- hosts: all
  become: yes
  become_user: fofi
  roles:
    - setup-dotfiles

- hosts: all
  become: yes
  become_user: manolis
  roles:
    - setup-dotfiles

- hosts: all
  become: yes
  become_user: theoni
  roles:
    - setup-dotfiles

- hosts: all
  become: yes
  become_user: petrina
  roles:
    - setup-dotfiles
