- hosts: all
  become: yes
  tasks:
    - name: update pacman cache
      pacman: update_cache=yes
    - name: create domus directory
      file: name="{{ thirdparty }}" group=domus mode='0775' state=directory
  roles:
    - setup-users
    - setup-thirdparty

- hosts: all
  become: yes
  roles:
    - { role: setup-base, become_user: dimitris}
    - { role: setup-dotfiles, become_user: dimitris }
    - { role: setup-dotfiles, become_user: fofi }
    - { role: setup-dotfiles, become_user: manolis }
    - { role: setup-dotfiles, become_user: theoni }
    - { role: setup-dotfiles, become_user: petrina }
    - setup-base
    - setup-dotfiles
    - setup-zsh
    - setup-desktop

- hosts: all
  become: yes
  become_user: fofi
  roles:
    - setup-zsh

- hosts: all
  become: yes
  become_user: manolis
  roles:
    - setup-zsh

- hosts: all
  become: yes
  become_user: theoni
  roles:
    - setup-zsh

- hosts: all
  become: yes
  become_user: petrina
  roles:
    - setup-zsh
