- pacman:
    name: git
    state: present

- copy:
    src: "~/Sync/Secret/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.ssh/{{ item }}"
    mode: 0600
  with_items:
    - id_rsa.pub
    - id_rsa

- git:
    repo: git@gitlab.com:DictumMortuum/notes.git
    dest: "{{ ansible_env.HOME }}/Notes"
    update: yes

- git:
    repo: git@gitlab.com:DictumMortuum/pass.git
    dest: "{{ ansible_env.HOME }}/.password-store"
    update: yes
