- hosts: all
  become: yes
  tasks:
    - name: create domus
      group:
        name: domus
        gid: 1992
        state: present

    - group:
        name: arcanum
        gid: 16180
        state: present

    - group:
        name: dimitris
        gid: 1986
        state: present

    - group:
        name: petrina
        gid: 1993
        state: present

    - group:
        name: manolis
        gid: 1956
        state: present

    - group:
        name: fofi
        gid: 1960
        state: present

    - group:
        name: theoni
        gid: 1989
        state: present

    - pacman:
        name: "{{ item }}"
        state: present
      loop:
        - zsh
        - sudo
        - vi

    - lineinfile:
        path: /etc/sudoers.d/dimitris
        state: present
        line: 'dimitris ALL=(ALL) NOPASSWD: ALL'
        create: True
        validate: /usr/sbin/visudo -cf %s

    - user:
        name: dimitris
        group: dimitris
        groups: arcanum,domus
        append: yes
        uid: 1986
        create_home: True
        comment: "Dimitris Raviolos,,,"
        shell: /bin/zsh
        password: "{{ 'default' | password_hash('sha512') }}"
        update_password: on_create
      register: dimitris

    - user:
        name: petrina
        group: petrina
        groups: domus
        append: yes
        uid: 1993
        create_home: True
        comment: "Petrina Raviolou,,,"
        shell: /bin/zsh
        password: "{{ 'default' | password_hash('sha512') }}"
        update_password: on_create
      register: petrina

    - shell: chage -d 0 petrina
      when: petrina.changed

    - user:
        name: manolis
        group: manolis
        groups: domus
        append: yes
        uid: 1956
        create_home: True
        comment: "Manolis Raviolos,,,"
        shell: /bin/zsh

    - shell: passwd -d manolis

    - user:
        name: fofi
        group: fofi
        groups: domus
        append: yes
        uid: 1960
        create_home: True
        comment: "Fofi Klironomou,,,"
        shell: /bin/zsh

    - shell: passwd -d fofi

    - user:
        name: theoni
        group: theoni
        groups: domus
        append: yes
        uid: 1989
        create_home: True
        comment: "Theoni Fytrou,,,"
        shell: /bin/zsh
        password: "{{ 'default' | password_hash('sha512') }}"
        update_password: on_create
      register: theoni

    - shell: chage -d 0 theoni
      when: theoni.changed
