#!/bin/bash

ARG=${1:-en}
IFACE=$(ls /sys/class/net | grep $ARG | tail -n 1)
[[ -z $IFACE ]] && exit 1
IP=$(ip -4 addr show $IFACE | awk '/inet/ {print $2}')
[[ -z $IP ]] && exit 1

case $BLOCK_BUTTON in
  3) echo -n "$IP" | xclip ;;
esac

echo "$IP"
